config/routes.rb
Rails.application.routes.draw do
#  devise_for :admins
  devise_for :admins, module: 'admins', controllers: {sessions: 'admins/sessions', registrations:'admins/registrations'}

#  devise_for :users
  devise_for :users, module: 'users', controllers: {sessions: 'users/sessions', registrations:'users/registrations'}

  # These are the protected routes.
  # The pages controller is for the user model and the
  # admin_pages is for the admin model
  get '/secret', to: 'pages#secret', as: :secret
  get '/adminsecret', to: 'admin_pages#secret', as: :adminsecret
  get '/adminhome', to: 'admin_pages#index'

  # Define the root for when a user is authenticated
  authenticated :user do
    root 'pages#index', as: :authenticated_user_root
  end

  # Define the root for when an admin is authenticated
  authenticated :admin do
    root 'admin_pages#index', as: :authenticated_admin_root
  end

  # default root (should never use this)
  root to: 'pages#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  before_action :authenticate_admin!
  layout 'adminlayout'

  def index
  end
end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController
  # disable default no_authentication action
  skip_before_action :require_no_authentication, only: [:new, :create, :cancel]

  protected

  #def sign_up(resource_name, resource)
    # just overwrite the default one
    # to prevent auto sign in as the new sign up
  #end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  # disable default no_authentication action
  skip_before_action :require_no_authentication, only: [:new, :create, :cancel]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  respond_to :html, :json

  # the layout should be specified by the resource (i.e. admin or user)
  layout :layout_by_resource

  protected

  # ensure name is allowed
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  # if we are using a devise controller then we can check the resource_name and return the appropriate layout
  def layout_by_resource
    puts "LayoutByResource: IS DEVISE CONTROLLER?: #{devise_controller?}"
    if devise_controller?
      puts "LayoutByResource - Resource name:#{resource_name}"
    end
    if devise_controller? && resource_name == :admin
      puts 'LayoutByResource is returning adminlayout'
      'adminlayout'
    elsif devise_controller? && resource_name == :account
      puts 'LayoutByResource is returning accountlayout'
      'accountlayout'
    elsif devise_controller? && resource_name == :user
      'userlayout'
    else
      puts 'LayoutByResource is returning application'
      'application'
    end
  end

  # Specify where to go after successful login again this is dictated by the resource that logged in
  def after_sign_in_path_for(resource)
    puts "AfterSignIn: IS DEVISE CONTROLLER?: #{devise_controller?}"
    puts "AfterSignIn - Resource: #{resource}"
    if devise_controller?
      puts "AfterSignIn - Resource name: #{resource_name}"
    end
    if devise_controller? && resource_name == :admin
      puts 'AfterSignIn is returning authenticated_admin_root_path'
      authenticated_admin_root_path
    elsif devise_controller? && resource_name == :account
      puts 'AfterSignIn is returning authenticated_account_root_path'
      authenticated_account_root_path
    elsif devise_controller? && resource_name == :user
      authenticated_user_root_path
    else
      puts 'AfterSignIn is returning root_path'
      root_path
    end
  end

  # Specify where to go after successful logout again this is dictated by the resource that logged in
  def after_sign_out_path_for(resource)
    puts "AfterSignOut: IS DEVISE CONTROLLER?: #{devise_controller?}"
    puts "AfterSignOut - Resource: #{resource}"
    if devise_controller?
      puts "AfterSignOut - Resource name: #{resource_name}"
    end
    if devise_controller? && resource_name == :admin
      puts 'AfterSignOut is returning new_admin_session_path'
      new_admin_session_path
    elsif devise_controller? && resource_name == :account
      puts 'AfterSignOut is returning new_account_session_path'
      new_account_session_path
    elsif devise_controller? && resource_name == :user
      new_user_session_path
    else
      puts 'AfterSignOut is returning application'
      'application'
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  layout 'userlayout'
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # disable default no_authentication action
  skip_before_action :require_no_authentication, only: [:new, :create, :cancel]

  protected

  def sign_up(resource_name, resource)
    # just overwrite the default one
    # to prevent auto sign in as the new sign up
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # disable default no_authentication action
  skip_before_action :require_no_authentication, only: [:new, :create, :cancel]
end

app/helpers/application_helper.rb
module ApplicationHelper

  def header(text)
    content_for(:header) { text.to_s}
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin_pages/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h1>Admin Welcome!</h1>
<!--      < if admin_signed_in? %>
        <p>Admin Register to get started.</p>
        <p>
          <= link_to 'Admin Register', new_admin_registration_path, class: 'btn btn-primary btn-lg' %>
        </p>
      < end %> -->
    </div>
  </div>
<% end %>

app/views/admin_pages/secret.html.erb
<% header 'Admin Secret!' %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/adminlayout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseTwoModelTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbr-header">
      <ul class="nav navbar-nav">
        <% if admin_signed_in? %>
            <% if action_name != 'index' %>
                <li><%= link_to 'Admin Home', root_path %></li>
            <% end %>
            <% if action_name != 'secret' %>
              <li><%= link_to 'Admin Secret', adminsecret_path %></li>
            <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if admin_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_admin.email %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <!--<li><= link_to 'Admin Profile', edit_admin_registration_path %></li> %> -->
              <li><%= link_to 'Admin Log out', destroy_admin_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
            <% if action_name != 'new' %>
              <li><%= link_to 'Admin Log In', new_admin_session_path %></li>
            <% end %>
          <li><%= link_to 'Admin Sign Up', new_admin_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
      <% end %>
</div>

<%= yield :top_content %>

<div class="container">
  <h1><%= yield :header %></h1>
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseTwoModelTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbr-header">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Default Home', root_path %></li>
        <% if account_signed_in? %>
          <li><%= link_to 'Default Secret', secret_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if account_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_account.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Default Profile', edit_account_registration_path %></li>
              <li><%= link_to 'Default Log out', destroy_account_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Default Log In', new_account_session_path %></li>
          <li><%= link_to 'Default Sign Up', new_account_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
      <% end %>
</div>

<%= yield :top_content %>

<div class="container">
  <h1><%= yield :header %></h1>
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/userlayout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseTwoModelTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbr-header">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
            Current User: <%= current_user.email %><br/>
            <% if action_name != 'index' %>
                <li><%= link_to 'User Home', authenticated_user_root_path %></li>
            <% end %>
            <% if action_name != 'secret' %>
                <li><%= link_to 'User Secret', secret_path %></li>
            <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.email %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'User Profile', edit_user_registration_path %></li>
                <li><%= link_to 'User Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <% if action_name != 'new' %>
                <li><%= link_to 'User Log In', new_user_session_path %></li>
            <% end %>
        <% end %>
      </ul>

    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">
  <h1><%= yield :header %></h1>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h1>/views/pages/index User Welcome!</h1>
      <% if !user_signed_in? %>
        <p>Register to get started.</p>
        <p>
          <%= link_to 'User Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
        </p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/pages/secret.html.erb
<% header 'User Secret!' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>